export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS';
export const RECEIVE_PRODUCT = 'RECEIVE_PRODUCT';
export const SET_CUSTOMER = 'SET_CUSTOMER';
export const SET_CART = 'SET_CART';
export const UPDATE_CART_ITEM = 'UPDATE_CART_ITEM';
export const CHECKOUT_START = 'CHECKOUT_START';
export const CHECKOUT_END = 'CHECKOUT_END';
